### PR TITLE
Continue the execution on push error

### PR DESCRIPTION
**Pull request by hosy**
Added skip command to to ignore error messages and continue the execution

Because of this git push error:
https://drone.owncloud.com/owncloud/translation-sync/895/1/2

### CODE REVIEW

**Comment by dschmidt** [comment]
Why does this error happen in the first place?

**Comment by tboerger** [comment]
Please fix the translation files instead of ignoring errors.

**Comment by hosy** [comment]
@tboerger translation files having the correct syntax. Same line ending, same text encoding as the other project `*.strings` files. I cannot find any syntax error.

**Comment by tboerger** [comment]
But we still need to find the fix instead of simply ignoring all errors for the translation sync. Beside that, since we are using Drone >=1.0.0 you could move the translation sync to the Drone pipeline within the iOS and Android repos.

**Comment by dschmidt** [comment]
For the record: this apparently was some kind of encoding issue and @hosy was able to properly fix it!

**Pull request closed without merging**
