### PR TITLE
Rename phoenix to web

### PR DESCRIPTION
**Pull request by micbar**
# Description

- Renaming the repo needs to be also renamed here.

### CODE REVIEW

**Comment by micbar** [comment]
@DeepDiver1975 is it possible to also rename the project in transifex?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 is it possible to also rename the project in transifex?

no idea ... let me check

**Comment by DeepDiver1975** [comment]
1. you need to update all tx config files - e.g. https://github.com/owncloud/web/blob/262cec1536156dae3281099aca2fde0febeec6e5/l10n/.tx/config#L4
2. project name can be changed - let me know how you want to name it
Screenshot from 2020-12-10 13-18-54

**Comment by micbar** [comment]
1. Yes. We have it on the radar.

2. Rename from `owncloud-phoenix` to `owncloud-web`

Can be renamed immediately.

**Comment by DeepDiver1975** [comment]
>     2\. Rename from `owncloud-phoenix` to `owncloud-web`

description?
ownCloud Web then?

**Comment by micbar** [comment]
ownCloud Web is perfect.

**Comment by DeepDiver1975** [comment]
renamed

Screenshot from 2020-12-10 14-05-12

**Comment by micbar** [comment]
The references in the tx config files have also been renamed. merging.

**Pull request merged**
